In [1]:
import numpy as np

In [10]:
a = [[1,0,1], [0,1,0], [1,1,1], [0,0,1]]

In [11]:
np.transpose(a)

array([[1, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 1, 1]])

In [12]:
counts = np.array([np.bincount(aa, minlength=2) for aa in np.transpose(a)])
counts

array([[2, 2],
       [2, 2],
       [1, 3]])

In [13]:
np.argmax(counts, axis=1)

array([0, 0, 1])

In [17]:
b = [0, 1, 1]
c = [1, 0, 1]

np.where(np.equal(b, c))

(array([2]),)